name: Deploy

on:
  pull_request:
    branches: [ "master" ]
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Dev
        run: yarn
          
      - name: Run deploy
        run: bash deploy.sh
